# -*- coding: utf-8 -*-
"""pense-em-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Um72yCwJ9EATC-nX90ySOC-FhQ2JqIMB

#Capitulo 1: jornada do programa

##1.3 -primeiro programa
"""

print("hello world")

'hello world!'

"""##1.4 operadores aritmeticos"""

40 + 2

43-2

6*7

6**2+6

6 ^ 2

